# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'homepage.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QDockWidget,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QProgressBar, QPushButton, QSizePolicy, QStackedWidget,
    QStatusBar, QTextBrowser, QTextEdit, QToolButton,
    QWidget)

class Ui_mw_home(object):
    def setupUi(self, mw_home):
        if not mw_home.objectName():
            mw_home.setObjectName(u"mw_home")
        mw_home.setEnabled(True)
        mw_home.resize(804, 603)
        self.actionclose = QAction(mw_home)
        self.actionclose.setObjectName(u"actionclose")
        self.centralwidget = QWidget(mw_home)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 0, 721, 541))
        self.homepage = QWidget()
        self.homepage.setObjectName(u"homepage")
        self.spend_label = QLabel(self.homepage)
        self.spend_label.setObjectName(u"spend_label")
        self.spend_label.setGeometry(QRect(340, 50, 81, 20))
        self.current_spend_goal = QProgressBar(self.homepage)
        self.current_spend_goal.setObjectName(u"current_spend_goal")
        self.current_spend_goal.setGeometry(QRect(320, 90, 118, 23))
        self.current_spend_goal.setValue(24)
        self.current_month_revenue = QLabel(self.homepage)
        self.current_month_revenue.setObjectName(u"current_month_revenue")
        self.current_month_revenue.setGeometry(QRect(100, 80, 141, 41))
        self.rev_title = QLabel(self.homepage)
        self.rev_title.setObjectName(u"rev_title")
        self.rev_title.setGeometry(QRect(90, 50, 151, 16))
        self.stackedWidget.addWidget(self.homepage)
        self.chatpage = QWidget()
        self.chatpage.setObjectName(u"chatpage")
        self.te_chathistory = QTextBrowser(self.chatpage)
        self.te_chathistory.setObjectName(u"te_chathistory")
        self.te_chathistory.setGeometry(QRect(0, 0, 731, 441))
        self.te_chatinput = QTextEdit(self.chatpage)
        self.te_chatinput.setObjectName(u"te_chatinput")
        self.te_chatinput.setGeometry(QRect(150, 450, 381, 81))
        self.bt_submitchat = QPushButton(self.chatpage)
        self.bt_submitchat.setObjectName(u"bt_submitchat")
        self.bt_submitchat.setGeometry(QRect(550, 450, 31, 71))
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoUp))
        self.bt_submitchat.setIcon(icon)
        self.stackedWidget.addWidget(self.chatpage)
        self.brandperformance = QWidget()
        self.brandperformance.setObjectName(u"brandperformance")
        self.de_startdate = QDateEdit(self.brandperformance)
        self.de_startdate.setObjectName(u"de_startdate")
        self.de_startdate.setGeometry(QRect(40, 40, 110, 22))
        self.de_startdate.setCalendarPopup(True)
        self.de_enddate = QDateEdit(self.brandperformance)
        self.de_enddate.setObjectName(u"de_enddate")
        self.de_enddate.setGeometry(QRect(160, 40, 110, 22))
        self.de_enddate.setCalendarPopup(True)
        self.cb_brandfilter = QComboBox(self.brandperformance)
        self.cb_brandfilter.setObjectName(u"cb_brandfilter")
        self.cb_brandfilter.setGeometry(QRect(330, 40, 171, 32))
        self.lbl_datefilter = QLabel(self.brandperformance)
        self.lbl_datefilter.setObjectName(u"lbl_datefilter")
        self.lbl_datefilter.setGeometry(QRect(50, 10, 61, 16))
        self.lbl_brandfilter = QLabel(self.brandperformance)
        self.lbl_brandfilter.setObjectName(u"lbl_brandfilter")
        self.lbl_brandfilter.setGeometry(QRect(350, 20, 61, 16))
        self.stackedWidget.addWidget(self.brandperformance)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.te_newcode = QTextEdit(self.page)
        self.te_newcode.setObjectName(u"te_newcode")
        self.te_newcode.setGeometry(QRect(90, 80, 191, 41))
        self.lbl_newcode = QLabel(self.page)
        self.lbl_newcode.setObjectName(u"lbl_newcode")
        self.lbl_newcode.setGeometry(QRect(90, 50, 71, 16))
        self.lbl_podcast = QLabel(self.page)
        self.lbl_podcast.setObjectName(u"lbl_podcast")
        self.lbl_podcast.setGeometry(QRect(90, 150, 71, 16))
        self.de_codestartdate = QDateEdit(self.page)
        self.de_codestartdate.setObjectName(u"de_codestartdate")
        self.de_codestartdate.setGeometry(QRect(90, 270, 110, 22))
        self.de_codestartdate.setCalendarPopup(True)
        self.lbl_newcodestartdate = QLabel(self.page)
        self.lbl_newcodestartdate.setObjectName(u"lbl_newcodestartdate")
        self.lbl_newcodestartdate.setGeometry(QRect(90, 240, 101, 16))
        self.cb_podcast = QComboBox(self.page)
        self.cb_podcast.setObjectName(u"cb_podcast")
        self.cb_podcast.setGeometry(QRect(90, 180, 201, 32))
        self.lbl_newcodeenddate = QLabel(self.page)
        self.lbl_newcodeenddate.setObjectName(u"lbl_newcodeenddate")
        self.lbl_newcodeenddate.setGeometry(QRect(90, 310, 101, 16))
        self.de_codeenddate = QDateEdit(self.page)
        self.de_codeenddate.setObjectName(u"de_codeenddate")
        self.de_codeenddate.setGeometry(QRect(90, 350, 110, 22))
        self.de_codeenddate.setCalendarPopup(True)
        self.bt_submitnewcode = QPushButton(self.page)
        self.bt_submitnewcode.setObjectName(u"bt_submitnewcode")
        self.bt_submitnewcode.setGeometry(QRect(90, 410, 100, 32))
        self.cb_existingcodes = QComboBox(self.page)
        self.cb_existingcodes.setObjectName(u"cb_existingcodes")
        self.cb_existingcodes.setGeometry(QRect(510, 80, 191, 32))
        self.lbl_newcode_2 = QLabel(self.page)
        self.lbl_newcode_2.setObjectName(u"lbl_newcode_2")
        self.lbl_newcode_2.setGeometry(QRect(510, 50, 91, 16))
        self.lbl_podcast_2 = QLabel(self.page)
        self.lbl_podcast_2.setObjectName(u"lbl_podcast_2")
        self.lbl_podcast_2.setGeometry(QRect(510, 130, 71, 16))
        self.cb_podcastsuspendcode = QComboBox(self.page)
        self.cb_podcastsuspendcode.setObjectName(u"cb_podcastsuspendcode")
        self.cb_podcastsuspendcode.setGeometry(QRect(510, 160, 191, 32))
        self.bt_suspendcode = QPushButton(self.page)
        self.bt_suspendcode.setObjectName(u"bt_suspendcode")
        self.bt_suspendcode.setGeometry(QRect(510, 220, 100, 32))
        self.lbl_newcode_3 = QLabel(self.page)
        self.lbl_newcode_3.setObjectName(u"lbl_newcode_3")
        self.lbl_newcode_3.setGeometry(QRect(470, 310, 91, 16))
        self.te_newcode_2 = QTextEdit(self.page)
        self.te_newcode_2.setObjectName(u"te_newcode_2")
        self.te_newcode_2.setGeometry(QRect(470, 350, 191, 41))
        self.bt_submitnewpodcast = QPushButton(self.page)
        self.bt_submitnewpodcast.setObjectName(u"bt_submitnewpodcast")
        self.bt_submitnewpodcast.setGeometry(QRect(470, 420, 121, 32))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.cb_brandspendgoal = QComboBox(self.page_2)
        self.cb_brandspendgoal.setObjectName(u"cb_brandspendgoal")
        self.cb_brandspendgoal.setGeometry(QRect(60, 70, 191, 32))
        self.cb_podcastspendgoal = QComboBox(self.page_2)
        self.cb_podcastspendgoal.setObjectName(u"cb_podcastspendgoal")
        self.cb_podcastspendgoal.setGeometry(QRect(60, 150, 191, 32))
        self.lbl_brandspendgoal = QLabel(self.page_2)
        self.lbl_brandspendgoal.setObjectName(u"lbl_brandspendgoal")
        self.lbl_brandspendgoal.setGeometry(QRect(70, 50, 58, 16))
        self.lbl_podcastspendgoal = QLabel(self.page_2)
        self.lbl_podcastspendgoal.setObjectName(u"lbl_podcastspendgoal")
        self.lbl_podcastspendgoal.setGeometry(QRect(70, 130, 58, 16))
        self.te_spengoal = QTextEdit(self.page_2)
        self.te_spengoal.setObjectName(u"te_spengoal")
        self.te_spengoal.setGeometry(QRect(70, 250, 104, 41))
        self.lbl_spendgoal = QLabel(self.page_2)
        self.lbl_spendgoal.setObjectName(u"lbl_spendgoal")
        self.lbl_spendgoal.setGeometry(QRect(70, 220, 101, 16))
        self.bt_spendgoal = QPushButton(self.page_2)
        self.bt_spendgoal.setObjectName(u"bt_spendgoal")
        self.bt_spendgoal.setGeometry(QRect(70, 330, 131, 32))
        self.lbl_actualspendbrand = QLabel(self.page_2)
        self.lbl_actualspendbrand.setObjectName(u"lbl_actualspendbrand")
        self.lbl_actualspendbrand.setGeometry(QRect(510, 50, 58, 16))
        self.cb_brandactualspend = QComboBox(self.page_2)
        self.cb_brandactualspend.setObjectName(u"cb_brandactualspend")
        self.cb_brandactualspend.setGeometry(QRect(500, 70, 211, 32))
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(510, 120, 58, 16))
        self.cb_podcastactualspend = QComboBox(self.page_2)
        self.cb_podcastactualspend.setObjectName(u"cb_podcastactualspend")
        self.cb_podcastactualspend.setGeometry(QRect(500, 150, 211, 32))
        self.bt_updtspendgoal = QPushButton(self.page_2)
        self.bt_updtspendgoal.setObjectName(u"bt_updtspendgoal")
        self.bt_updtspendgoal.setGeometry(QRect(70, 380, 131, 32))
        self.lbl_actualspend = QLabel(self.page_2)
        self.lbl_actualspend.setObjectName(u"lbl_actualspend")
        self.lbl_actualspend.setGeometry(QRect(510, 210, 101, 16))
        self.te_actualspend = QTextEdit(self.page_2)
        self.te_actualspend.setObjectName(u"te_actualspend")
        self.te_actualspend.setGeometry(QRect(500, 250, 104, 41))
        self.bt_submitactualspend = QPushButton(self.page_2)
        self.bt_submitactualspend.setObjectName(u"bt_submitactualspend")
        self.bt_submitactualspend.setGeometry(QRect(490, 330, 151, 32))
        self.bt_updtactualspend = QPushButton(self.page_2)
        self.bt_updtactualspend.setObjectName(u"bt_updtactualspend")
        self.bt_updtactualspend.setGeometry(QRect(490, 390, 151, 32))
        self.stackedWidget.addWidget(self.page_2)
        mw_home.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mw_home)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 804, 24))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.file = QMenu(self.menubar)
        self.file.setObjectName(u"file")
        self.file.setEnabled(True)
        mw_home.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(mw_home)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(False)
        self.statusbar.setSizeGripEnabled(False)
        mw_home.setStatusBar(self.statusbar)
        self.w_dock = QDockWidget(mw_home)
        self.w_dock.setObjectName(u"w_dock")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_dock.sizePolicy().hasHeightForWidth())
        self.w_dock.setSizePolicy(sizePolicy)
        self.w_dock.setMinimumSize(QSize(40, 38))
        font = QFont()
        font.setPointSize(9)
        self.w_dock.setFont(font)
        self.w_dock.setFeatures(QDockWidget.DockWidgetFeature.NoDockWidgetFeatures)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.bt_home = QToolButton(self.dockWidgetContents)
        self.bt_home.setObjectName(u"bt_home")
        self.bt_home.setGeometry(QRect(10, 10, 31, 31))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoHome))
        self.bt_home.setIcon(icon1)
        self.bt_chat = QToolButton(self.dockWidgetContents)
        self.bt_chat.setObjectName(u"bt_chat")
        self.bt_chat.setGeometry(QRect(10, 60, 31, 31))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.WeatherStorm))
        self.bt_chat.setIcon(icon2)
        self.bt_brandperformance = QToolButton(self.dockWidgetContents)
        self.bt_brandperformance.setObjectName(u"bt_brandperformance")
        self.bt_brandperformance.setGeometry(QRect(10, 110, 31, 31))
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MailMarkImportant))
        self.bt_brandperformance.setIcon(icon3)
        self.bt_settings = QToolButton(self.dockWidgetContents)
        self.bt_settings.setObjectName(u"bt_settings")
        self.bt_settings.setGeometry(QRect(10, 490, 31, 31))
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.HelpAbout))
        self.bt_settings.setIcon(icon4)
        self.bt_codepodcastinput = QToolButton(self.dockWidgetContents)
        self.bt_codepodcastinput.setObjectName(u"bt_codepodcastinput")
        self.bt_codepodcastinput.setGeometry(QRect(10, 160, 31, 31))
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaEject))
        self.bt_codepodcastinput.setIcon(icon5)
        self.bt_spendinput = QToolButton(self.dockWidgetContents)
        self.bt_spendinput.setObjectName(u"bt_spendinput")
        self.bt_spendinput.setGeometry(QRect(10, 210, 31, 31))
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditPaste))
        self.bt_spendinput.setIcon(icon6)
        self.w_dock.setWidget(self.dockWidgetContents)
        mw_home.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.w_dock)

        self.menubar.addAction(self.file.menuAction())
        self.file.addAction(self.actionclose)

        self.retranslateUi(mw_home)

        self.stackedWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(mw_home)
    # setupUi

    def retranslateUi(self, mw_home):
        mw_home.setWindowTitle(QCoreApplication.translate("mw_home", u"MainWindow", None))
        self.actionclose.setText(QCoreApplication.translate("mw_home", u"close", None))
        self.spend_label.setText(QCoreApplication.translate("mw_home", u"spend goal", None))
        self.current_month_revenue.setText(QCoreApplication.translate("mw_home", u"TextLabel", None))
        self.rev_title.setText(QCoreApplication.translate("mw_home", u"Curent Monthly Revenue", None))
        self.bt_submitchat.setText("")
        self.lbl_datefilter.setText(QCoreApplication.translate("mw_home", u"date filter", None))
        self.lbl_brandfilter.setText(QCoreApplication.translate("mw_home", u"brand", None))
        self.lbl_newcode.setText(QCoreApplication.translate("mw_home", u"new code", None))
        self.lbl_podcast.setText(QCoreApplication.translate("mw_home", u"podcast", None))
        self.lbl_newcodestartdate.setText(QCoreApplication.translate("mw_home", u"code start date", None))
        self.lbl_newcodeenddate.setText(QCoreApplication.translate("mw_home", u"code end date", None))
        self.bt_submitnewcode.setText(QCoreApplication.translate("mw_home", u"submit code", None))
        self.lbl_newcode_2.setText(QCoreApplication.translate("mw_home", u"Exisiting code", None))
        self.lbl_podcast_2.setText(QCoreApplication.translate("mw_home", u"podcast", None))
        self.bt_suspendcode.setText(QCoreApplication.translate("mw_home", u"suspend code", None))
        self.lbl_newcode_3.setText(QCoreApplication.translate("mw_home", u"new podcast", None))
        self.bt_submitnewpodcast.setText(QCoreApplication.translate("mw_home", u"submit podcast", None))
        self.lbl_brandspendgoal.setText(QCoreApplication.translate("mw_home", u"brand", None))
        self.lbl_podcastspendgoal.setText(QCoreApplication.translate("mw_home", u"podcast", None))
        self.lbl_spendgoal.setText(QCoreApplication.translate("mw_home", u"spend goal", None))
        self.bt_spendgoal.setText(QCoreApplication.translate("mw_home", u"submit spend goal", None))
        self.lbl_actualspendbrand.setText(QCoreApplication.translate("mw_home", u"brand", None))
        self.label_5.setText(QCoreApplication.translate("mw_home", u"podcast", None))
        self.bt_updtspendgoal.setText(QCoreApplication.translate("mw_home", u"update spend goal", None))
        self.lbl_actualspend.setText(QCoreApplication.translate("mw_home", u"actual spend", None))
        self.bt_submitactualspend.setText(QCoreApplication.translate("mw_home", u"submit actual spend", None))
        self.bt_updtactualspend.setText(QCoreApplication.translate("mw_home", u"update actual spend", None))
        self.file.setTitle(QCoreApplication.translate("mw_home", u"file", None))
        self.w_dock.setWindowTitle(QCoreApplication.translate("mw_home", u"podscale", None))
        self.bt_home.setText(QCoreApplication.translate("mw_home", u"...", None))
        self.bt_chat.setText(QCoreApplication.translate("mw_home", u"...", None))
        self.bt_brandperformance.setText(QCoreApplication.translate("mw_home", u"...", None))
        self.bt_settings.setText(QCoreApplication.translate("mw_home", u"...", None))
        self.bt_codepodcastinput.setText(QCoreApplication.translate("mw_home", u"...", None))
        self.bt_spendinput.setText(QCoreApplication.translate("mw_home", u"...", None))
    # retranslateUi

